version: 1.0
provider:
  name: openfaas
  gateway: http://gateway.openfaas.local
functions:
  matrixfunction:
    lang: node12
    handler: ./matrixfunction
    image: mabuaisha/matrixfunction:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 20
    environment:
      read_timeout: 5m5s
      write_timeout: 5m5s
# Only relevant for K8S
    secrets:
      - dockerhub