experiment:
  server: gateway.openfaas.local
  port: 80
  number_of_runs: 2
  delay_between_runs: 2 # The format in minute
  number_of_requests: 40000
  replicas:
    - 1
    - 10
    - 20
  concurrency:
    - 2
    - 5
    - 15
    - 25
  result_dir: /home/centos/result

functions:
  - name: fibfunction
    cold_start: true
    idle_duration: 15 # the format in minute
    yaml_path: functions/warm-starts-scenarios/k8s/fibfunction.yml
    api:
      uri: function/fibfunction
      param: 25
      http_method: GET

  - name: gofunction
    yaml_path: functions/runtimes-scenarios/go/k8s/gofunction.yml
    api:
      uri: function/gofunction
      http_method: POST

  - name: javafunction
    yaml_path: functions/runtimes-scenarios/java/k8s/javafunction.yml
    api:
      uri: function/javafunction
      http_method: POST

  - name: nodefunction
    yaml_path: functions/runtimes-scenarios/nodejs/k8s/nodefunction.yml
    api:
      uri: function/nodefunction
      http_method: POST

  - name: pythonfunction
    yaml_path: functions/runtimes-scenarios/python/k8s/pythonfunction.yml
    api:
      uri: function/pythonfunction
      http_method: POST

  - name: ftpfunction
    yaml_path: functions/computation-scenarios/network/k8s/ftpfunction.yml
    api:
      uri: function/ftpfunction
      http_method: GET

  - name: matrixfunction
    yaml_path: functions/computation-scenarios/matrix/k8s/matrixfunction.yml
    api:
      uri: function/matrixfunction
      param: 300
      http_method: GET

  - name: iofunction
    yaml_path: functions/computation-scenarios/io/k8s/iofunction.yml
    api:
      uri: function/iofunction
      http_method: POST
      data: >
        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
        Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
        when an unknown printer took a galley of type and scrambled it to make a type
        specimen book. It has survived not only five centuries, but also the leap
        into electronic typesetting, remaining essentially unchanged.
        It was popularised in the 1960s with the release of Letraset sheets containing
        Lorem Ipsum passages, and more recently with desktop publishing software
        like Aldus PageMaker including versions of Lorem Ipsum.

  - name: consumerfunction
    yaml_path: functions/composite-scenarios/consumer/k8s/consumerfunction.yml
    api:
      uri: function/consumerfunction
      param: 300
      http_method: GET