version: 1.0
provider:
  name: openfaas
  gateway: http://gateway.openfaas.local
functions:
  fibfunction:
    lang: node12
    handler: ./fibfunction
    image: mabuaisha/fibfunction:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 20
      com.openfaas.scale.zero: true
    # Only relevant for K8S
    secrets:
      - dockerhub