version: 1.0
provider:
  name: openfaas
  gateway: http://gateway.openfaas.local
functions:
  pythonfunction:
    lang: python3
    handler: ./pythonfunction
    image: mabuaisha/pythonfunction:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 20
# Only relevant for K8S
    secrets:
      - dockerhub


