version: 1.0
provider:
  name: openfaas
  gateway: http://gateway.openfaas.local
functions:
  pythonfunction:
    lang: python3
    handler: ./pythonfunction
    image: mabuaisha/pythonfunction:latest
# Only relevant for K8S
    secrets:
      - dockerhub


