version: 1.0
provider:
  name: openfaas
  # The ip should be changed
  # The port 31112 is only applied for k8s
  gateway: http://127.0.0.1:31112
functions:
  pythonfunction:
    lang: python3
    handler: ./pythonfunction
    image: mabuaisha/pythonfunction:latest
# Only relevant for K8S
    secrets:
      - dockerhub


