version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  ftpfunction:
    lang: node12
    handler: ./ftpfunction
    image: mabuaisha/ftpfunction:latest
    environment:
      write_debug: true
# Only relevant for K8S
    secrets:
      - dockerhub

