version: 1.0
provider:
  name: openfaas
  # The ip should be changed
  gateway: http://gateway.openfaas.local
functions:
  gofunction:
    lang: go
    handler: ./gofunction
    image: mabuaisha/gofunction:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 20
    environment:
      read_timeout: 5m5s
      write_timeout: 5m5s
# Only relevant for K8S
    secrets:
      - dockerhub