version: 1.0
provider:
  name: openfaas
  gateway: http://gateway.openfaas.local
functions:
  javafunction:
    lang: java8
    handler: ./javafunction
    image: mabuaisha/javafunction:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 20
# Only relevant for K8S
    secrets:
      - dockerhub
