experiment:
  server: gateway.openfaas.local
  port: 80
  number_of_runs: 6
  number_of_requests: 35000
  delay_between_runs: 1
  replicas:
    - 1
    - 10
    - 20
  concurrency:
    - 5
    - 10
    - 20
    - 50
  result_dir: /home/centos/result

functions:
  - name: fibfunction
    # This is must be set as to the same value that configured for idler on docker swarm and k8s
    # For sake of simplicity the inactivity_duration set for k8s to 5minutes
    inactivity_duration: 5
    # This param means that the number_of_requests (total) will be sent over 7 chunks.
    # For example if number_of_requests = 35000 then for each chunk we are going to send 35000/7 = 5000 requests
    # This is added in order to see the effect of the cold start time between each chunk
    chunks_number: 7
    yaml_path: functions/warm-starts-scenarios/k8s/fibfunction.yml
    environment:
      read_timeout: 5m5s
      write_timeout: 5m5s
    api:
      uri: function/fibfunction
      # The range of values that param can take from 5 - 40
      # This min/max values will be used by the Random function provided by jmeter
      param:
        min: 5
        max: 40
      http_method: POST

  - name: gofunction
    yaml_path: functions/runtimes-scenarios/go/k8s/gofunction.yml
    environment:
      read_timeout: 5m5s
      write_timeout: 5m5s
    api:
      uri: function/gofunction
      http_method: POST

  - name: javafunction
    yaml_path: functions/runtimes-scenarios/java/k8s/javafunction.yml
    environment:
      read_timeout: 5m5s
      write_timeout: 5m5s
    api:
      uri: function/javafunction
      http_method: POST

  - name: nodefunction
    yaml_path: functions/runtimes-scenarios/nodejs/k8s/nodefunction.yml
    environment:
      read_timeout: 5m5s
      write_timeout: 5m5s
    api:
      uri: function/nodefunction
      http_method: POST

  - name: pythonfunction
    yaml_path: functions/runtimes-scenarios/python/k8s/pythonfunction.yml
    environment:
      read_timeout: 5m5s
      write_timeout: 5m5s
    api:
      uri: function/pythonfunction
      http_method: POST

  - name: iofunction
    yaml_path: functions/computation-scenarios/io/k8s/iofunction.yml
    environment:
      read_timeout: 5m5s
      write_timeout: 5m5s
    api:
      uri: function/iofunction
      http_method: POST
      data: >
        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
        Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
        when an unknown printer took a galley of type and scrambled it to make a type
        specimen book. It has survived not only five centuries, but also the leap
        into electronic typesetting, remaining essentially unchanged.
        It was popularised in the 1960s with the release of Letraset sheets containing
        Lorem Ipsum passages, and more recently with desktop publishing software
        like Aldus PageMaker including versions of Lorem Ipsum.



  - name: matrixfunction
    yaml_path: functions/computation-scenarios/matrix/k8s/matrixfunction.yml
    environment:
      read_timeout: 5m5s
      write_timeout: 5m5s
    api:
      uri: function/matrixfunction
      # The range of values that param can take from 5 - 40
      # This min/max values will be used by the Random function provided by jmeter
      param:
        min: 10
        max: 200
      http_method: POST

  - name: consumerfunction
    yaml_path: functions/composite-scenarios/consumer/nomad/consumerfunction.yml
    environment:
      read_timeout: 5m5s
      write_timeout: 5m5s
      gateway_endpoint: http://gateway.openfaas:8080
    api:
      uri: function/consumerfunction
      # The range of values that param can take from 5 - 40
      # This min/max values will be used by the Random function provided by jmeter
      param:
        min: 5
        max: 150
      http_method: POST
    depends_on: matrixfunction

  - name: ftpfunction
    yaml_path: functions/computation-scenarios/network/k8s/ftpfunction.yml
    environment:
      read_timeout: 5m5s
      write_timeout: 5m5s
      # FTP HOST
      ftp_host: 10.0.2.163
      # FTP user name, should match the value specified on terraform for ftp module
      ftp_user: ftpuser
      # FTP password, should match the value specified on terraform for ftp module
      ftp_password: ftppassword
    api:
      uri: function/ftpfunction
      http_method: POST
