version: 1.0
provider:
  name: openfaas
  # The ip should be changed
  # The port 31112 is only applied for k8s
  gateway: http://127.0.0.1:31112
functions:
  nodefunction:
    lang: node12
    handler: ./nodefunction
    image: mabuaisha/nodefunction:latest
# Only relevant for K8S
    secrets:
      - dockerhub
