version: 1.0
provider:
  name: openfaas
  # The ip should be changed
  # The port 31112 is only applied for k8s
  gateway: http://gateway.openfaas.local
functions:
  nodefunction:
    lang: node12
    handler: ./nodefunction
    image: mabuaisha/nodefunction:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 20
    environment:
      read_timeout: 5m5s
      write_timeout: 5m5s
      write_debug: true
# Only relevant for K8S
    secrets:
      - dockerhub
