version: 1.0
provider:
  name: openfaas
  gateway: http://gateway.openfaas.local
functions:
  iofunction:
    lang: node12
    handler: ./iofunction
    image: mabuaisha/iofunction:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 20
# Only relevant for K8S
    secrets:
      - dockerhub

