version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  iofunction:
    lang: node12
    handler: ./iofunction
    image: mabuaisha/iofunction:latest
# Only relevant for K8S
    secrets:
      - dockerhub

